[audio]
use-pipewire = true
seek-interval = 15
cross-fade-time = 700
device-buffer-ms = 80
avoid_resampling = false
resample-quality = 1
cache-limit = 1000
cache-use-tmp = true
precache-local-files = false
always-ffmpeg = false
volume-curve = 2
jump-start-dl = true

[locale]
display-language = "auto"

[search]
separate-multi-genre = false

[tag-editor]
tag-editor-name = "Picard"
tag-editor-target = "picard"

[playback]
playback-follow-cursor = false
spotify-prefer-web = false
spotify-allow-local = false
back-restarts = false
resume-on-advance = true
end-queue-stop = false
block-suspend = false
allow-video-formats = true

[HiDPI]
ui-scale = 1.15
auto-scale = false
tracklist-y-text-offset = 0

[ui]
theme-name = "Charmed"
transparent-style = 1
mac-style = true
allow-art-zoom = true
scroll-gallery-by-row = true
scroll-gallery-distance = 90
scroll-spectrogram = true
mascot-opacity = 40
synced-lyrics-time-offset = 0
artist-list-prefers-album-artist = true
side-panel-info-persists = false
side-panel-info-selected = false
side-panel-info-selected-always = false
mini-mode-avoid-notifications = false
hide-queue-when-empty = true
show-current-on-transition = false
enable-art-header-bar = true
always-art-header-bar = false
showcase-texture-background = false
side-panel-style = 1
side-lyrics-art = true
side-lyrics-art-on-top = false
absolute-track-indices = false
auto-hide-bottom-title = true
auto-show-playing = false
notify-include-album = true
show-rating-hint = true
drag-tab-to-unpin = true

[gallery]
gallery-thin-borders = false
increase-row-spacing = false
gallery-center-text = false

[fonts]
use-custom-fonts = true
font-main-standard = "DejaVu Sans Mono,"
font-main-medium = "DejaVu Sans Mono,"
font-main-bold = "DejaVu Sans Mono,"
font-main-condensed = "DejaVu Sans Mono,"
font-main-condensed-bold = "DejaVu Sans Mono,"

[tracklist]
double-digit-indices = false
column-album-artist-fallsback = false
left-aligned-album-artist-title = false
import-auto-sort = false

[transcode]
sync-bypass-transcode = false
sync-bypass-low-bitrate = true
radio-record-codec = "OPUS"

[directories]
sync-device-music-dir = ""
encode-output-dir = ""
add_download_directory = ""
playlist_folder_path = ""
autoscan_playlist_folder = false

[app]
enable-remote-interface = false
use-gamepad = true
use-system-tray = true
hide-maximize-button = false
restore-window-position = true
mini-mode-always-on-top = true
enable-mpris = true
resume-playback-on-restart = false
resume-playback-on-wake = false
auto-dl-artist-data = true
fanart.tv-cover = false
fanart.tv-artist = false
fanart.tv-background = false
auto-update-playlists = true
write-ratings-to-tag = false
enable-spotify = false
enable-discord-rpc = true
auto-search-lyrics = false
shortcuts-ignore-keymap = false
alpha_key_activate_search = true

[tokens]
discogs-personal-access-token = ""
custom-listenbrainz-url = ""
listenbrainz-token = ""

[tauon_satellite]
tau-url = ""

[lastfm]
lastfm-pull-love = false

[maloja_account]
maloja-url = ""
maloja-key = ""
maloja-enable = false

[plex_account]
plex-username = ""
plex-password = ""
plex-servername = ""

[subsonic_account]
subsonic-username = ""
subsonic-password = ""
subsonic-password-plain = false
subsonic-server-url = "http://localhost:4040"

[koel_account]
koel-username = "admin@example.com"
koel-password = "admin"
koel-server-url = "http://localhost:8050"

[jellyfin_account]
jelly-username = ""
jelly-password = ""
jelly-server-url = "http://localhost:8096"

[network]
stream-bitrate = 0

[listenalong]
broadcast-page-port = 7590

[chart]
chart-columns = 3
chart-rows = 3
chart-uses-text = true
chart-sorts-top-played = true
chart-font = "Monospace 10"
