# Core Colors
background            #0a0a05
foreground            #f3d1d6
selection_background  #ed3372
selection_foreground  #0a0a05
url_color             #ea718d
cursor                #ed3372
# Tabs
active_tab_background   #301921
active_tab_foreground   #f3d1d6
inactive_tab_background #0a0a05
inactive_tab_foreground #3d4653
# Windows
active_border_color     #ed3372
inactive_border_color   #301921
# Terminal Colors (ANSI)
# Black
color0  #301921
color8  #a9b2c0
# Red
color1  #ed3372
color9  #ea718d
# Green
color2  #d2929e
color10 #f3d1d6
# Yellow
color3  #d18190
color11 #EA718D
# Blue
color4  #D2929E
color12 #d2929e
# Magenta
color5  #ea718d
color13 #ed3372
# Cyan
color6  #EA718D
color14 #f3d1d6
# White
color7  #f3d1d6
color15 #ffffff
