; ---
; librepup's Gameplay Info:
;  - Global Audio Offset: 21ms
;  - Visual Offset: -21ms
; ---

[General]
Name = Akuma Nihmune++
Author = librepup
UseSkinBackgrounds = True
CenterCursor = False

[MainMenu]
; Top and Bottom Lines
BackgroundLineColor = 145,60,154
ForegroundLineColor = 145,60,154
; Buttons
ButtonTextColor = 150,150,150
ButtonTextHoveredColor = 255,255,255
; Navigation Elements
NavigationButtonTextColor = 255,255,255
NavigationQuitButtonTextColor = 255,2,44
; Tips
TipTitleColor = 255,255,255
TipTextColor = 255,255,255
; News
NewsTitleColor = 255,255,255
NewsDateColor = 236,51,114
NewsTextColor = 255,255,255
; Jukebox
JukeboxProgressBarColor = 255,255,255

[MenuBorder]
; Top and Bottom Lines
BackgroundLineColor = 145,60,154
ForegroundLineColor = 145,60,154
; Top and Bottom Buttons
ButtonTextColor = 150,150,150
ButtonTextHoveredColor = 255,255,255

[SongSelect]
; Leaderboard
LeaderboardTitleColor = 255,255,255
LeaderboardRankingTitleColor = 255,255,255
LeaderboardDropdownColor = 236,51,114
LeaderboardStatusTextColor = 255,255,255
LeaderboardScoreColorEven = 6,1,9
LeaderboardScoreColorOdd = 6,1,9
LeaderboardScoreRankColor = 255,255,255
LeaderboardScoreRatingColor = 240,240,240
LeaderboardScoreAccuracyColor = 240,240,240
LeaderboardScoreUsernameSelfColor = 2,171,255
LeaderboardScoreUsernameOtherColor = 0,119,178
; Backgrounds
DisplayMapBackground = True
MapBackgroundBrightness = 100
; Panels
MapsetPanelSongTitleColor = 255,255,255
MapsetPanelSongArtistColor = 2,171,255
MapsetPanelCreatorColor = 2,171,255
MapsetPanelByColor = 2,171,255
MapsetPanelBannerSize = 426,86

[Results]
ResultsBackgroundType = Background

[4K]
; Rating
RatingDisplayScale = 18
RatingDisplayPosX = 10
RatingDisplayPosY = 8
; General
HitBubblesScale = 0
FlipNoteImagesOnUpscroll = True
BgMaskAlpha = 1
ColorObjectsBySnapDistance = True
ReceptorsOverHitObjects = True
TimingLineColor = 255,255,255 ; 201,67,178 - Pink
; Judgement
JudgementBurstPosY = -80
JudgementCounterAlpha = 1
JudgementCounterFontColor = 255,255,255
JudgementCounterSize = 0
JudgementHitBurstBumpY = 0
JudgementHitBurstScale = 50
; Stage
StageReceptorPadding = 0
HitPosOffsetY = 150
NotePadding = 0
TimingBarPixelSize = 2
ReceptorPosOffsetY = 0
; Columns
ColumnColor1 = 255,255,255
ColumnColor2 = 235,179,216
ColumnColor3 = 235,179,216
ColumnColor4 = 255,255,255
ColumnAlignment = 0
ColumnLightingScale = 1.5f
ColumnLightingOffsetY = 114
ColumnSize = 100
; Hit Lighting
HitLightingY = 0
HitLightingWidth = 0
HitLightingHeight = 0
; Score Display
ScoreDisplayPosX = 10
ScoreDisplayPosY = 5
; Accuracy Display
AccuracyDisplayScale = 17.5
AccuracyDisplayPosX = -10
AccuracyDisplayPosY = 5
; Keys per Second Display
KpsDisplayPosX = -10
KpsDisplayPosY = 10
; Health Bar
HealthBarType = Vertical
HealthBarKeysAlignment = RightStage
; Hit Error
HitErrorHeight = 25
HitErrorChevronSize = 10
HitErrorAlpha = 0.5
HitErrorPosY = 325
DrawLongNoteEnd = True
HealthBarScale = 40
; Combo
ComboPosY = -120
