foreground #ff3271
background #0a0a05
cursor #ec8a8f
color0 #f4788a
color1 #d58bb6
color2 #f87d73
color3 #f97c86
color4 #fc8083
color5 #f97c89
color6 #f87577
color7 #ec8a8f
color8 #f4788a
color9 #d58bb6
color10 #f87d73
color11 #f97c86
color12 #fc8083
color13 #f97c89
color14 #f87577
color15 #ec8a8f
# Tabs
active_tab_foreground    #FFFFFF
active_tab_background    #ff3271
inactive_tab_foreground  #ec8a8f
inactive_tab_background  #0a0a05
