# Mappings
map ctrl+shift+j send_text normal,application sh -c 'export TERM=xterm-old && notify-send "Terminal Mode" "Set Terminal to Fallback"; clear'\r
map ctrl+shift+g send_text normal,application sh -c 'export TERM=xterm-kitty && notify-send "Terminal Mode" "Set Terminal to Kitty"; clear'\r
